scrape_configs:
  - job_name: varlogs
    static_configs:
      - targets: [localhost]
        labels:
          job: varlogs
          __path__: /var/log/*log
  - job_name: applogs

# remote_write:
#   - url: http://mimir-nginx.monitoring.svc:80/prometheus/api/v1/push
