
default:
  envOverrides:
    - name: OTEL_COLLECTOR_NAME
      value: http://tempo-query-frontend.monitoring.svc.cluster.local:3100

opentelemetry-collector:
  enabled: false

jaeger:
  enabled: false

prometheus:
  enabled: false

grafana:
  enabled: false