global:
  clusterDomain: 'cluster.local'

multitenancyEnabled: false

gateway:
  enabled: true

minio:
  enabled: true

storage:
  trace:
    backend: local

traces:
  otlp:
    http:
      enabled: true
    grpc:
      enabled: true

distributor:
  config:
    log_received_spans:
      enabled: true

metricsGenerator:
  enabled: true
  config:
    storage:
      remote_write:
        - url: http://prometheus-community-kube-prometheus.monitoring.svc:9090/api/v1/write

global_overrides:
  metrics_generator_processors:
    - service-graphs
    - span-metrics
