# Reference:
# https://grafana.com/docs/helm-charts/tempo-distributed/next/get-started-helm-charts/
global:
  clusterDomain: 'cluster.local'
gateway:
  enabled: true
minio:
  enabled: true

storage:
  trace:
    backend: s3
    s3:
      bucket: aws-eks-demo-default-otel-tempo-bucket
      endpoint: s3.amazonaws.com
      region: us-east-1
      insecure: true
traces:
  otlp:
    grpc:
      enabled: true
    http:
      enabled: true
  zipkin:
    enabled: false
  jaeger:
    thriftHttp:
      enabled: false
  opencensus:
    enabled: false

metrics_generator:
  # enabled: true
  config:
    service_graphs_max_items: 15000
    storage_remote_write:
      - url: http://prometheus-community-kube-prometheus.monitoring.svc:9090/prometheus/api/v1/write

global_overrides:
  metrics_generator_processors:
    - service-graphs
    - span-metrics
